# Generated by Django 3.2.5 on 2021-07-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothpayment', '0003_cartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
