# Generated by Django 3.2.5 on 2021-07-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothpayment', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
